package vn.nganluong.naba.entities;
// Generated Nov 1, 2020 4:13:02 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * ChannelFunction generated by hbm2java
 */
@Entity
@Table(name = "channel_function", uniqueConstraints = @UniqueConstraint(columnNames = {
		"channel_id", "code", "name" }))
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class ChannelFunction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7779110211857688669L;
	private Integer id;
	private Channel channel;
	private String code;
	private String name;
	private String host;
	private String url;
	private String port;
	private String authKey;
	private String authUser;
	private String authPassword;
	private String user;
	private String password;
	private String config;
	private Date timeCreated;
	private Date timeUpdated;
	private Boolean status;
	private Set<PgLogChannelFunction> pgLogChannelFunctions = new HashSet<PgLogChannelFunction>(0);

	public ChannelFunction() {
	}

	public ChannelFunction(Channel channel, String code) {
		this.channel = channel;
		this.code = code;
	}

	public ChannelFunction(Channel channel, String code, String name, String host, String url, String port,
			String authKey, String authUser, String authPassword, String user, String password, String config, Date timeCreated,
			Date timeUpdated, Boolean status, Set<PgLogChannelFunction> pgLogChannelFunctions) {
		this.channel = channel;
		this.code = code;
		this.name = name;
		this.host = host;
		this.url = url;
		this.port = port;
		this.authKey = authKey;
		this.authUser = authUser;
		this.authPassword = authPassword;
		this.user = user;
		this.password = password;
		this.config = config;
		this.timeCreated = timeCreated;
		this.timeUpdated = timeUpdated;
		this.status = status;
		this.pgLogChannelFunctions = pgLogChannelFunctions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "channel_id", nullable = false)
	public Channel getChannel() {
		return this.channel;
	}

	public void setChannel(Channel channel) {
		this.channel = channel;
	}

	@Column(name = "code", nullable = false, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "host")
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "port", length = 8)
	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	@Column(name = "auth_key")
	public String getAuthKey() {
		return this.authKey;
	}

	public void setAuthKey(String authKey) {
		this.authKey = authKey;
	}

	@Column(name = "auth_user")
	public String getAuthUser() {
		return this.authUser;
	}

	public void setAuthUser(String authUser) {
		this.authUser = authUser;
	}

	@Column(name = "auth_password")
	public String getAuthPassword() {
		return this.authPassword;
	}

	public void setAuthPassword(String authPassword) {
		this.authPassword = authPassword;
	}

	@Column(name = "user")
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@Column(name = "config", length = 500)
	public String getConfig() {
		return config;
	}

	public void setConfig(String config) {
		this.config = config;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", length = 19)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_updated", length = 19)
	public Date getTimeUpdated() {
		return this.timeUpdated;
	}

	public void setTimeUpdated(Date timeUpdated) {
		this.timeUpdated = timeUpdated;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "channelFunction")
	public Set<PgLogChannelFunction> getPgLogChannelFunctions() {
		return this.pgLogChannelFunctions;
	}

	public void setPgLogChannelFunctions(Set<PgLogChannelFunction> pgLogChannelFunctions) {
		this.pgLogChannelFunctions = pgLogChannelFunctions;
	}

}
