package vn.nganluong.naba.entities;
// Generated Nov 1, 2020 4:13:02 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Channel generated by hbm2java
 */
@Entity
@Table(name = "channel", uniqueConstraints = { @UniqueConstraint(columnNames = "code"),
		@UniqueConstraint(columnNames = "name") })
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class Channel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4596562710003691136L;
	private Integer id;
	private String name;
	private String code;
	private boolean status;
	private Set<ChannelFunction> channelFunctions = new HashSet<ChannelFunction>(0);
//	private Set<Payment> payments = new HashSet<Payment>(0);

	public Channel() {
	}

	public Channel(String name, String code, boolean status) {
		this.name = name;
		this.code = code;
		this.status = status;
	}

	public Channel(String name, String code, boolean status, Set<ChannelFunction> channelFunctions) {
		this.name = name;
		this.code = code;
		this.status = status;
		this.channelFunctions = channelFunctions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", unique = true, nullable = false, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "channel")
	public Set<ChannelFunction> getChannelFunctions() {
		return this.channelFunctions;
	}

	public void setChannelFunctions(Set<ChannelFunction> channelFunctions) {
		this.channelFunctions = channelFunctions;
	}
}
