package vn.nganluong.naba.entities;
// Generated Dec 15, 2020, 3:58:49 PM by Hibernate Tools 5.2.12.Final

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PaymentAccount generated by hbm2java
 */
@Entity
@Table(name = "payment_account", uniqueConstraints = @UniqueConstraint(columnNames = { "id",
		"user_id", "channel_id" }))
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class PaymentAccount implements java.io.Serializable {

	private Integer id;
	private int userId;
	private int channelId;
	private String description;
	private String username;
	private String password;
	private String cif;
	private String sourceAccountNo;
	private String providerId;
	private String merchantId;
	private String merchantName;
	private String authKey;
	private String encryptKey;
	private String urlApi;
	private String urlConfirm;
	private String privateKeyPath;
	private String publicKeyPath;
	private String partnerKeyPath;
	private String httpAuthCallback;
	private String encryptKeyCallback;
	private String virtualAccountCode;
	private byte status;

	public PaymentAccount() {
	}

	public PaymentAccount(int userId, int channelId, byte status) {
		this.userId = userId;
		this.channelId = channelId;
		this.status = status;
	}

	public PaymentAccount(int userId, int channelId, String description, String username, String password, String cif,
			String sourceAccountNo, String providerId, String merchantId, String merchantName, String authKey,
			String encryptKey, String urlApi, String urlConfirm, String privateKeyPath, String publicKeyPath,
			String partnerKeyPath, String httpAuthCallback, String encryptKeyCallback, String virtualAccountCode, byte status) {
		this.userId = userId;
		this.channelId = channelId;
		this.description = description;
		this.username = username;
		this.password = password;
		this.cif = cif;
		this.sourceAccountNo = sourceAccountNo;
		this.providerId = providerId;
		this.merchantId = merchantId;
		this.merchantName = merchantName;
		this.authKey = authKey;
		this.encryptKey = encryptKey;
		this.urlApi = urlApi;
		this.urlConfirm = urlConfirm;
		this.privateKeyPath = privateKeyPath;
		this.publicKeyPath = publicKeyPath;
		this.partnerKeyPath = partnerKeyPath;
		this.httpAuthCallback = httpAuthCallback;
		this.encryptKeyCallback = encryptKeyCallback;
		this.virtualAccountCode = virtualAccountCode;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "channel_id", nullable = false)
	public int getChannelId() {
		return this.channelId;
	}

	public void setChannelId(int channelId) {
		this.channelId = channelId;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 500)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "cif", length = 45)
	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name = "source_account_no", length = 45)
	public String getSourceAccountNo() {
		return this.sourceAccountNo;
	}

	public void setSourceAccountNo(String sourceAccountNo) {
		this.sourceAccountNo = sourceAccountNo;
	}

	@Column(name = "provider_id")
	public String getProviderId() {
		return this.providerId;
	}

	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	@Column(name = "merchant_id")
	public String getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "merchant_name")
	public String getMerchantName() {
		return this.merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	@Column(name = "auth_key")
	public String getAuthKey() {
		return this.authKey;
	}

	public void setAuthKey(String authKey) {
		this.authKey = authKey;
	}

	@Column(name = "encrypt_key")
	public String getEncryptKey() {
		return this.encryptKey;
	}

	public void setEncryptKey(String encryptKey) {
		this.encryptKey = encryptKey;
	}

	@Column(name = "url_api", length = 500)
	public String getUrlApi() {
		return this.urlApi;
	}

	public void setUrlApi(String urlApi) {
		this.urlApi = urlApi;
	}

	@Column(name = "url_confirm", length = 500)
	public String getUrlConfirm() {
		return this.urlConfirm;
	}

	public void setUrlConfirm(String urlConfirm) {
		this.urlConfirm = urlConfirm;
	}

	@Column(name = "private_key_path")
	public String getPrivateKeyPath() {
		return this.privateKeyPath;
	}

	public void setPrivateKeyPath(String privateKeyPath) {
		this.privateKeyPath = privateKeyPath;
	}

	@Column(name = "public_key_path")
	public String getPublicKeyPath() {
		return this.publicKeyPath;
	}

	public void setPublicKeyPath(String publicKeyPath) {
		this.publicKeyPath = publicKeyPath;
	}

	@Column(name = "partner_key_path")
	public String getPartnerKeyPath() {
		return this.partnerKeyPath;
	}

	public void setPartnerKeyPath(String partnerKeyPath) {
		this.partnerKeyPath = partnerKeyPath;
	}

	@Column(name = "http_auth_callback", length = 100)
	public String getHttpAuthCallback() {
		return this.httpAuthCallback;
	}

	public void setHttpAuthCallback(String httpAuthCallback) {
		this.httpAuthCallback = httpAuthCallback;
	}

	@Column(name = "encrypt_key_callback", length = 100)
	public String getEncryptKeyCallback() {
		return this.encryptKeyCallback;
	}

	public void setEncryptKeyCallback(String encryptKeyCallback) {
		this.encryptKeyCallback = encryptKeyCallback;
	}

	@Column(name = "virtual_account_code", length = 40)
	public String getVirtualAccountCode() {
		return virtualAccountCode;
	}

	public void setVirtualAccountCode(String virtualAccountCode) {
		this.virtualAccountCode = virtualAccountCode;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
