package vn.nganluong.naba.entities;
// Generated Nov 1, 2020 4:13:02 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PaymentChannel generated by hbm2java
 */
@Entity
@Table(name = "payment_channel", uniqueConstraints = @UniqueConstraint(columnNames = { "name",
		"hanlder_file_class" }))
public class PaymentChannel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8985733804271222828L;
	private Integer id;
	private String name;
	private String url;
	private String host;
	private Integer port;
	private String hanlderFileClass;
	private String handlerFilePath;
	private int bankId;
	private byte typeChannel;
	private byte status;

	public PaymentChannel() {
	}

	public PaymentChannel(String name, int bankId, byte typeChannel, byte status) {
		this.name = name;
		this.bankId = bankId;
		this.typeChannel = typeChannel;
		this.status = status;
	}

	public PaymentChannel(String name, String url, String host, Integer port, String hanlderFileClass,
			String handlerFilePath, int bankId, byte typeChannel, byte status) {
		this.name = name;
		this.url = url;
		this.host = host;
		this.port = port;
		this.hanlderFileClass = hanlderFileClass;
		this.handlerFilePath = handlerFilePath;
		this.bankId = bankId;
		this.typeChannel = typeChannel;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "host")
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "port")
	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	@Column(name = "hanlder_file_class")
	public String getHanlderFileClass() {
		return this.hanlderFileClass;
	}

	public void setHanlderFileClass(String hanlderFileClass) {
		this.hanlderFileClass = hanlderFileClass;
	}

	@Column(name = "handler_file_path")
	public String getHandlerFilePath() {
		return this.handlerFilePath;
	}

	public void setHandlerFilePath(String handlerFilePath) {
		this.handlerFilePath = handlerFilePath;
	}

	@Column(name = "bank_id", nullable = false)
	public int getBankId() {
		return this.bankId;
	}

	public void setBankId(int bankId) {
		this.bankId = bankId;
	}

	@Column(name = "type_channel", nullable = false)
	public byte getTypeChannel() {
		return this.typeChannel;
	}

	public void setTypeChannel(byte typeChannel) {
		this.typeChannel = typeChannel;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
