package vn.nganluong.naba.entities;
// Generated Nov 1, 2020 4:13:02 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.ToString;
import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment")
@Builder
@AllArgsConstructor
@ToString
public class Payment implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 509679784362650397L;
	private Integer id;
	private Integer channelId;
	private Integer pgFunctionId;
	private int paymentType;
	private String merchantCode;
	private String merchantName;
	private String clientRequestId;
	private String merchantTransactionId;
	private String channelTransactionId;
	private String channelTransactionSeq;
	private String channelStatus;
	private String channelMessage;
	private BigDecimal amount;
	private Integer channelTransactionStatus;
	private Integer merchantTransactionStatus;
	private Integer pgTransactionStatus;
	private String accountNo;
	private String virtualAccountNo;
	private String cardNo;
	private Integer pgErrorId;
	private Integer revertStatus;
	private String description;
	private String rawRequest;
	private String rawResponse;
	private Date timeCreated;
	private Date timeUpdated;
	private String channelTransactionType;
	private String sourceAccount;
	private int cardType;

	public Payment() {
	}

	public Payment(int channelId, Integer pgFunctionId, Integer paymentType, String merchantCode, String merchantName,
				   String clientRequestId, String merchantTransactionId, String channelTransactionId, String channelTransactionSeq,
				   String channelStatus,
				   String channelMessage, BigDecimal amount, Integer channelTransactionStatus, Integer merchantTransactionStatus,
				   Integer pgTransactionStatus, String accountNo, String virtualAccountNo, String cardNo, Integer pgErrorId,
				   Integer revertStatus, String description, String rawRequest, String rawResponse, Date timeCreated, Date timeUpdated
			, String channelTransactionType, String sourceAccount) {
		this.channelId = channelId;
		this.pgFunctionId = pgFunctionId;
		this.paymentType = paymentType;
		this.merchantCode = merchantCode;
		this.merchantName = merchantName;
		this.clientRequestId = clientRequestId;
		this.merchantTransactionId = merchantTransactionId;
		this.channelTransactionId = channelTransactionId;
		this.channelTransactionSeq = channelTransactionSeq;
		this.channelStatus = channelStatus;
		this.channelMessage = channelMessage;
		this.amount = amount;
		this.channelTransactionStatus = channelTransactionStatus;
		this.merchantTransactionStatus = merchantTransactionStatus;
		this.pgTransactionStatus = pgTransactionStatus;
		this.accountNo = accountNo;
		this.virtualAccountNo = virtualAccountNo;
		this.cardNo = cardNo;
		this.pgErrorId = pgErrorId;
		this.description = description;
		this.revertStatus = revertStatus;
		this.rawRequest = rawRequest;
		this.rawResponse = rawResponse;
		this.timeCreated = timeCreated;
		this.timeUpdated = timeUpdated;
		this.channelTransactionType = channelTransactionType;
		this.sourceAccount = sourceAccount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "channel_id", nullable = false)
	public Integer getChannelId() {
		return channelId;
	}

	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	@Column(name = "pg_function_id")
	public Integer getPgFunctionId() {
		return pgFunctionId;
	}

	public void setPgFunctionId(Integer pgFunctionId) {
		this.pgFunctionId = pgFunctionId;
	}

	@Column(name = "payment_type", nullable = false)
	public int getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(int paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "merchant_code", length = 45)
	public String getMerchantCode() {
		return this.merchantCode;
	}

	public void setMerchantCode(String merchantCode) {
		this.merchantCode = merchantCode;
	}

	@Column(name = "merchant_name")
	public String getMerchantName() {
		return this.merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	@Column(name = "client_request_id", length = 50)
	public String getClientRequestId() {
		return this.clientRequestId;
	}

	public void setClientRequestId(String clientRequestId) {
		this.clientRequestId = clientRequestId;
	}

	@Column(name = "merchant_transaction_id", unique = true, nullable = false, length = 50)
	public String getMerchantTransactionId() {
		return this.merchantTransactionId;
	}

	public void setMerchantTransactionId(String merchantTransactionId) {
		this.merchantTransactionId = merchantTransactionId;
	}

	@Column(name = "channel_transaction_id", length = 45)
	public String getChannelTransactionId() {
		return this.channelTransactionId;
	}

	public void setChannelTransactionId(String channelTransactionId) {
		this.channelTransactionId = channelTransactionId;
	}

	@Column(name = "channel_transaction_seq", length = 45)
	public String getChannelTransactionSeq() {
		return channelTransactionSeq;
	}

	public void setChannelTransactionSeq(String channelTransactionSeq) {
		this.channelTransactionSeq = channelTransactionSeq;
	}

	@Column(name = "channel_status", length = 50)
	public String getChannelStatus() {
		return this.channelStatus;
	}

	public void setChannelStatus(String channelStatus) {
		this.channelStatus = channelStatus;
	}

	@Column(name = "channel_message")
	public String getChannelMessage() {
		return this.channelMessage;
	}

	public void setChannelMessage(String channelMessage) {
		this.channelMessage = channelMessage;
	}

	@Column(name = "amount")
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "channel_transaction_status", nullable = false)
	@ColumnDefault(value = "0")
	public Integer getChannelTransactionStatus() {
		return channelTransactionStatus;
	}

	public void setChannelTransactionStatus(Integer channelTransactionStatus) {
		this.channelTransactionStatus = channelTransactionStatus;
	}

	@Column(name = "merchant_transaction_status", nullable = false)
	@ColumnDefault(value = "0")
	public Integer getMerchantTransactionStatus() {
		return merchantTransactionStatus;
	}

	public void setMerchantTransactionStatus(Integer merchantTransactionStatus) {
		this.merchantTransactionStatus = merchantTransactionStatus;
	}

	@Column(name = "pg_transaction_status", nullable = false)
	@ColumnDefault(value = "0")
	public Integer getPgTransactionStatus() {
		return pgTransactionStatus;
	}

	public void setPgTransactionStatus(Integer pgTransactionStatus) {
		this.pgTransactionStatus = pgTransactionStatus;
	}

	@Column(name = "account_no")
	public String getAccountNo() {
		return accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "virtual_account_no", length = 60)
	public String getVirtualAccountNo() {
		return this.virtualAccountNo;
	}

	public void setVirtualAccountNo(String virtualAccountNo) {
		this.virtualAccountNo = virtualAccountNo;
	}

	@Column(name = "card_no")
	public String getCardNo() {
		return cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "pg_error_id")
	public Integer getPgErrorId() {
		return this.pgErrorId;
	}

	public void setPgErrorId(Integer pgErrorId) {
		this.pgErrorId = pgErrorId;
	}

	@Column(name = "revert_status")
	public Integer getRevertStatus() {
		return this.revertStatus;
	}

	public void setRevertStatus(Integer revertStatus) {
		this.revertStatus = revertStatus;
	}

	@Column(name = "description", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
//	@CreationTimestamp
	@Column(name = "time_created", length = 19)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@UpdateTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_updated", length = 19)
	public Date getTimeUpdated() {
		return this.timeUpdated;
	}

	public void setTimeUpdated(Date timeUpdated) {
		this.timeUpdated = timeUpdated;
	}

	@Column(name = "raw_request")
	public String getRawRequest() {
		return rawRequest;
	}

	public void setRawRequest(String rawRequest) {
		this.rawRequest = rawRequest;
	}

	@Column(name = "raw_response")
	public String getRawResponse() {
		return rawResponse;
	}

	public void setRawResponse(String rawResponse) {
		this.rawResponse = rawResponse;
	}

	@Column(name = "channel_transaction_type", length = 45)
	public String getChannelTransactionType() {
		return this.channelTransactionType;
	}

	public void setChannelTransactionType(String channelTransactionType) {
		this.channelTransactionType = channelTransactionType;
	}

	@Column(name = "source_account", length = 45)
	public String getSourceAccount() {
		return this.sourceAccount;
	}

	public void setSourceAccount(String sourceAccount) {
		this.sourceAccount = sourceAccount;
	}

	@Column(name = "card_type", nullable = false)
	public int getCardType() {
		return cardType;
	}

	public void setCardType(int cardType) {
		this.cardType = cardType;
	}
}
