package vn.nganluong.naba.entities;
// Generated Nov 1, 2020 4:13:02 PM by Hibernate Tools 5.2.12.Final

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgEndpoint generated by hbm2java
 */
@Entity
@Table(name = "pg_endpoint", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class PgEndpoint implements java.io.Serializable {

	private Integer id;
	private String name;
	private String ip;
	private String authKey;
	private String httpUser;
	private String httpPassword;
	private Boolean test;
	private Byte status;

	public PgEndpoint() {
	}

	public PgEndpoint(String name, String ip, String authKey) {
		this.name = name;
		this.ip = ip;
		this.authKey = authKey;
	}

	public PgEndpoint(String name, String ip, String authKey, String httpUser, String httpPassword, Boolean test,
			Byte status) {
		this.name = name;
		this.ip = ip;
		this.authKey = authKey;
		this.httpUser = httpUser;
		this.httpPassword = httpPassword;
		this.test = test;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ip", nullable = false, length = 200)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "auth_key", nullable = false, length = 50)
	public String getAuthKey() {
		return this.authKey;
	}

	public void setAuthKey(String authKey) {
		this.authKey = authKey;
	}

	@Column(name = "http_user", length = 50)
	public String getHttpUser() {
		return this.httpUser;
	}

	public void setHttpUser(String httpUser) {
		this.httpUser = httpUser;
	}

	@Column(name = "http_password", length = 50)
	public String getHttpPassword() {
		return this.httpPassword;
	}

	public void setHttpPassword(String httpPassword) {
		this.httpPassword = httpPassword;
	}

	@Column(name = "test")
	public Boolean getTest() {
		return this.test;
	}

	public void setTest(Boolean test) {
		this.test = test;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
