package vn.nganluong.naba.entities;
// Generated Dec 1, 2020 10:42:10 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PgMail generated by hbm2java
 */
@Entity
@Table(name = "pg_mail")
public class PgMail implements java.io.Serializable {

	private static final long serialVersionUID = 3316250339975585001L;
	private Integer id;
	private Integer channelId;
	private Integer pgFunctionId;
	private String host;
	private String userName;
	private String password;
	private Integer port;
	private String mailFromAddress;
	private String mailFromName;
	private String mailTo;
	private String mailCc;
	private String mailBc;
	private String subject;
	private String body;
	private String content;
	private Date timeCreated;
	private Boolean status;

	public PgMail() {
	}

	public PgMail(Integer channelId, Integer pgFunctionId, String host, String userName, String password, Integer port,
			String mailFromAddress, String mailFromName, String mailTo, String mailCc, String mailBc, String subject,
			String body, String content, Date timeCreated, Boolean status) {
		this.channelId = channelId;
		this.pgFunctionId = pgFunctionId;
		this.host = host;
		this.userName = userName;
		this.password = password;
		this.port = port;
		this.mailFromAddress = mailFromAddress;
		this.mailFromName = mailFromName;
		this.mailTo = mailTo;
		this.mailCc = mailCc;
		this.mailBc = mailBc;
		this.subject = subject;
		this.body = body;
		this.content = content;
		this.timeCreated = timeCreated;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "channel_id")
	public Integer getChannelId() {
		return this.channelId;
	}

	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	@Column(name = "pg_function_id")
	public Integer getPgFunctionId() {
		return this.pgFunctionId;
	}

	public void setPgFunctionId(Integer pgFunctionId) {
		this.pgFunctionId = pgFunctionId;
	}

	@Column(name = "host")
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "port")
	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	@Column(name = "mail_from_address", length = 100)
	public String getMailFromAddress() {
		return this.mailFromAddress;
	}

	public void setMailFromAddress(String mailFromAddress) {
		this.mailFromAddress = mailFromAddress;
	}

	@Column(name = "mail_from_name", length = 100)
	public String getMailFromName() {
		return this.mailFromName;
	}

	public void setMailFromName(String mailFromName) {
		this.mailFromName = mailFromName;
	}

	@Column(name = "mail_to", length = 100)
	public String getMailTo() {
		return this.mailTo;
	}

	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}

	@Column(name = "mail_cc")
	public String getMailCc() {
		return this.mailCc;
	}

	public void setMailCc(String mailCc) {
		this.mailCc = mailCc;
	}

	@Column(name = "mail_bc")
	public String getMailBc() {
		return this.mailBc;
	}

	public void setMailBc(String mailBc) {
		this.mailBc = mailBc;
	}

	@Column(name = "subject", length = 1000)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "body", length = 2048)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "content", length = 2048)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", length = 19)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
