package vn.nganluong.naba.entities;
// Generated Nov 16, 2020 3:02:33 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PgSchedule generated by hbm2java
 */
@Entity
@Table(name = "pg_schedule")
public class PgSchedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1098953324709965077L;
	private Integer id;
	private int channelId;
	private Integer pgFunctionId;
	private String scheduleName;
	private String cronExpression;
	private String description;
	private Date timeCreated;
	private Boolean status;

	public PgSchedule() {
	}

	public PgSchedule(int channelId) {
		this.channelId = channelId;
	}

	public PgSchedule(int channelId, Integer pgFunctionId, String scheduleName, String cronExpression,
			String description, Date timeCreated, Boolean status) {
		this.channelId = channelId;
		this.pgFunctionId = pgFunctionId;
		this.scheduleName = scheduleName;
		this.cronExpression = cronExpression;
		this.description = description;
		this.timeCreated = timeCreated;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "channel_id", nullable = false)
	public int getChannelId() {
		return this.channelId;
	}

	public void setChannelId(int channelId) {
		this.channelId = channelId;
	}

	@Column(name = "pg_function_id")
	public Integer getPgFunctionId() {
		return this.pgFunctionId;
	}

	public void setPgFunctionId(Integer pgFunctionId) {
		this.pgFunctionId = pgFunctionId;
	}

	@Column(name = "schedule_name")
	public String getScheduleName() {
		return this.scheduleName;
	}

	public void setScheduleName(String scheduleName) {
		this.scheduleName = scheduleName;
	}

	@Column(name = "cron_expression", length = 45)
	public String getCronExpression() {
		return this.cronExpression;
	}

	public void setCronExpression(String cronExpression) {
		this.cronExpression = cronExpression;
	}

	@Column(name = "description", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", length = 19)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
