package vn.nganluong.naba.entities;
// Generated Dec 12, 2020, 4:50:37 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WebUsersRolesId generated by hbm2java
 */
@Embeddable
public class WebUsersRolesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5937542949724724087L;
	private int userId;
	private int roleId;

	public WebUsersRolesId() {
	}

	public WebUsersRolesId(int userId, int roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WebUsersRolesId))
			return false;
		WebUsersRolesId castOther = (WebUsersRolesId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
