
package gateway.core.channel.bidv.bidv_transfer_247.wstthdrecon;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TTHDOL_Recon", targetNamespace = "http://wsTTHDRecon")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TTHDOLRecon {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "submit")
    @WebResult(name = "submitReturn", targetNamespace = "")
    @RequestWrapper(localName = "submit", targetNamespace = "http://wsTTHDRecon", className = "wstthdrecon.Submit")
    @ResponseWrapper(localName = "submitResponse", targetNamespace = "http://wsTTHDRecon", className = "wstthdrecon.SubmitResponse")
    public String submit(
        @WebParam(name = "request", targetNamespace = "")
        String request);

}
