package gateway.core.channel.bidv.ws.bidvws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01
 * Generated source version: 2.2
 *
 */
@WebService(name = "NCC_PortType", targetNamespace = "BIDVWS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        gateway.core.channel.bidv.ws.message_confirm.ObjectFactory.class,
        gateway.core.channel.bidv.ws.message_confirm_wallet.ObjectFactory.class,
        gateway.core.channel.bidv.ws.nccinput_schema.ObjectFactory.class,
        gateway.core.channel.bidv.ws.nccoutput_schema.ObjectFactory.class,
        gateway.core.channel.bidv.ws.nccwalletinput_schema.ObjectFactory.class,
        gateway.core.channel.bidv.ws.nccwalletoutput_schema.ObjectFactory.class
})
public interface NCCPortType {


    /**
     *
     * @param input
     * @return
     *     returns message_confirm.MSG
     */
    @WebMethod(operationName = "Confirm", action = "/NCC_WSDL.serviceagent//Confirm")
    @WebResult(name = "MSG", targetNamespace = "MESSAGE_CONFIRM", partName = "output")
    public gateway.core.channel.bidv.ws.message_confirm.MSG confirm(
            @WebParam(name = "MSG", targetNamespace = "MESSAGE_CONFIRM", partName = "input")
                    gateway.core.channel.bidv.ws.message_confirm.MSG input);

    /**
     *
     * @param input
     * @return
     *     returns nccoutput_schema.Root
     */
    @WebMethod(action = "/WSDL-service2.serviceagent/NCC_PortTypeEndpoint2/verify")
    @WebResult(name = "root", targetNamespace = "NCCOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccoutput_schema.Root verify(
            @WebParam(name = "root", targetNamespace = "NCCInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccinput_schema.Root input);

    /**
     *
     * @param input
     * @return
     *     returns nccwalletoutput_schema.Root
     */
    @WebMethod(action = "/NCC_WSDL.serviceagent//link")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root link(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input);

    /**
     *
     * @param input
     * @return
     *     returns message_confirm_wallet.MSG
     */
    @WebMethod(action = "/NCC_WSDL.serviceagent//confirmWallet")
    @WebResult(name = "MSG", targetNamespace = "MESSAGE_CONFIRM_WALLET", partName = "output")
    public gateway.core.channel.bidv.ws.message_confirm_wallet.MSG confirmWallet(
            @WebParam(name = "MSG", targetNamespace = "MESSAGE_CONFIRM_WALLET", partName = "input")
                    gateway.core.channel.bidv.ws.message_confirm_wallet.MSG input);

    /**
     *
     * @param input
     * @return
     *     returns nccwalletoutput_schema.Root
     */
    @WebMethod(action = "/NCC_WSDL.serviceagent//wallet2Bank")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root wallet2Bank(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input);

    /**
     *
     * @param input
     * @return
     *     returns nccoutput_schema.Root
     */
    @WebMethod(action = "/WSDL-service2.serviceagent/NCC_PortTypeEndpoint2/inquiry")
    @WebResult(name = "root", targetNamespace = "NCCOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccoutput_schema.Root inquiry(
            @WebParam(name = "root", targetNamespace = "NCCInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccinput_schema.Root input);

    /**
     *
     * @param input
     * @return
     *     returns nccwalletoutput_schema.Root
     */
    @WebMethod(action = "/NCC_WSDL.serviceagent//bank2Wallet")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root bank2Wallet(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input);

    /**
     *
     * @param input
     * @return
     *     returns nccwalletoutput_schema.Root
     */
    @WebMethod(action = "/NCC_WSDL.serviceagent//unLink")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root unLink(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input);

    /**
     *
     * @param input
     * @return
     *     returns nccwalletoutput_schema.Root
     */
    @WebMethod(action = "/NCC_WSDL.serviceagent//checkOtp")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root checkOtp(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input);

    /**
     *
     * @param input
     * @return
     *     returns nccoutput_schema.Root
     */
    @WebMethod(action = "/WSDL-service2.serviceagent/NCC_PortTypeEndpoint2/refund")
    @WebResult(name = "root", targetNamespace = "NCCOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccoutput_schema.Root refund(
            @WebParam(name = "root", targetNamespace = "NCCInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccinput_schema.Root input);

    /**
     *
     * @param input
     * @return
     *     returns nccwalletoutput_schema.Root
     */
    @WebMethod(action = "/NCC_WSDL.serviceagent//checkLink")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root checkLink(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input);

    /**
     *
     * @param input
     * @return
     *     returns nccoutput_schema.Root
     */
    @WebMethod(action = "/WSDL-service2.serviceagent/NCC_PortTypeEndpoint2/inittrans")
    @WebResult(name = "root", targetNamespace = "NCCOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccoutput_schema.Root inittrans(
            @WebParam(name = "root", targetNamespace = "NCCInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccinput_schema.Root input);

    /**
     *
     * @param input
     * @return
     *     returns nccwalletoutput_schema.Root
     */
    @WebMethod(action = "/WSDL-service0.serviceagent/NCC_PortTypeEndpoint0/providerBalance")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root providerBalance(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input")
                    gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input);

    /**
     * ########################################## CHUYEN TIỀN 247
     * ##########################################
     *
     */
    @WebMethod(action = "/NCC_WSDL.serviceagent//GetBankList247")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root GetBankList247(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input") gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input);

    //    /**
//     * Hàm này được TGTT/NCCDV gọi để lấy thông tin Tên người hưởng tại ngân
//     * hàng ngoài BIDV dùng cho chi hộ chuyển tiền liên ngân hàng 24/7.
//     * */
    @WebMethod(action = "/NCC_WSDL.serviceagent//GetName247")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root GetName247(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input") gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input
    );

    @WebMethod(action = "/NCC_WSDL.serviceagent//Tranfer2Bank247")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root Tranfer2Bank247(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input") gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input
    );

    @WebMethod(action = "/NCC_WSDL.serviceagent//Tranfer2BankBIDV")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root Tranfer2BankBIDV(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input") gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input
    );

    @WebMethod(action = "/NCC_WSDL.serviceagent//GetNameBIDV")
    @WebResult(name = "root", targetNamespace = "NCCWalletOutput_Schema", partName = "Output")
    public gateway.core.channel.bidv.ws.nccwalletoutput_schema.Root GetNameBIDV(
            @WebParam(name = "root", targetNamespace = "NCCWalletInput_Schema", partName = "Input") gateway.core.channel.bidv.ws.nccwalletinput_schema.Root input
    );

}
