package vn.nganluong.naba.entities;
// Generated Nov 1, 2020 4:13:02 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * PgErrorDefinition generated by hbm2java
 */
@Entity
@Table(name = "pg_error_definition", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)  
public class PgErrorDefinition implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4637167755568408978L;
	private Integer id;
	private String code;
	private String message;
	private int channelId;
	private int pgFunctionId;
	private boolean status;
	private Integer paymentChannelId;

	public PgErrorDefinition() {
	}

	public PgErrorDefinition(String code, String message, int channelId, int pgFunctionId, boolean status) {
		this.code = code;
		this.message = message;
		this.channelId = channelId;
		this.pgFunctionId = pgFunctionId;
		this.status = status;
	}

	public PgErrorDefinition(String code, String message, int channelId, int pgFunctionId, boolean status,
			Integer paymentChannelId) {
		this.code = code;
		this.message = message;
		this.channelId = channelId;
		this.pgFunctionId = pgFunctionId;
		this.status = status;
		this.paymentChannelId = paymentChannelId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "message", nullable = false, length = 500)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "channel_id", nullable = false)
	public int getChannelId() {
		return this.channelId;
	}

	public void setChannelId(int channelId) {
		this.channelId = channelId;
	}

	@Column(name = "pg_function_id", nullable = false)
	public int getPgFunctionId() {
		return this.pgFunctionId;
	}

	public void setPgFunctionId(int pgFunctionId) {
		this.pgFunctionId = pgFunctionId;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "payment_channel_id")
	public Integer getPaymentChannelId() {
		return this.paymentChannelId;
	}

	public void setPaymentChannelId(Integer paymentChannelId) {
		this.paymentChannelId = paymentChannelId;
	}

}
