package vn.nganluong.naba.entities;
// Generated Nov 13, 2020 3:15:59 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * PgFunction generated by hbm2java
 */
@Entity
@Table(name = "pg_function", uniqueConstraints = @UniqueConstraint(columnNames = {"code", "channel_id"}))
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class PgFunction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7453273122531937915L;
	private Integer id;
	private Integer channelId;
	private String code;
	private String name;
	private String logMsgPatternRequestSuccess;
	private String logMsgPatternRequestError;
	private String logMsgPatternResponseSuccess;
	private String logMsgPatternResponseError;
	private boolean status;

	public PgFunction() {
	}

	public PgFunction(String code, boolean status) {
		this.code = code;
		this.status = status;
	}

	public PgFunction(Integer channelId, String code, String name, String logMsgPatternRequestSuccess,
			String logMsgPatternRequestError, String logMsgPatternResponseSuccess, String logMsgPatternResponseError,
			boolean status) {
		this.channelId = channelId;
		this.code = code;
		this.name = name;
		this.logMsgPatternRequestSuccess = logMsgPatternRequestSuccess;
		this.logMsgPatternRequestError = logMsgPatternRequestError;
		this.logMsgPatternResponseSuccess = logMsgPatternResponseSuccess;
		this.logMsgPatternResponseError = logMsgPatternResponseError;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "channel_id")
	public Integer getChannelId() {
		return this.channelId;
	}

	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "log_msg_pattern_request_success", length = 512)
	public String getLogMsgPatternRequestSuccess() {
		return this.logMsgPatternRequestSuccess;
	}

	public void setLogMsgPatternRequestSuccess(String logMsgPatternRequestSuccess) {
		this.logMsgPatternRequestSuccess = logMsgPatternRequestSuccess;
	}

	@Column(name = "log_msg_pattern_request_error", length = 512)
	public String getLogMsgPatternRequestError() {
		return this.logMsgPatternRequestError;
	}

	public void setLogMsgPatternRequestError(String logMsgPatternRequestError) {
		this.logMsgPatternRequestError = logMsgPatternRequestError;
	}

	@Column(name = "log_msg_pattern_response_success", length = 512)
	public String getLogMsgPatternResponseSuccess() {
		return this.logMsgPatternResponseSuccess;
	}

	public void setLogMsgPatternResponseSuccess(String logMsgPatternResponseSuccess) {
		this.logMsgPatternResponseSuccess = logMsgPatternResponseSuccess;
	}

	@Column(name = "log_msg_pattern_response_error", length = 512)
	public String getLogMsgPatternResponseError() {
		return this.logMsgPatternResponseError;
	}

	public void setLogMsgPatternResponseError(String logMsgPatternResponseError) {
		this.logMsgPatternResponseError = logMsgPatternResponseError;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
