package vn.nganluong.naba.entities;
// Generated Nov 1, 2020 4:13:02 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * PgLogChannelFunction generated by hbm2java
 */
@Entity
@Table(name = "pg_log_channel_function", uniqueConstraints = @UniqueConstraint(columnNames = "channel_function_id"))
public class PgLogChannelFunction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2795173810277689942L;
	private Integer id;
	private ChannelFunction channelFunction;
	private String userCode;
	private Integer requestTotal;
	private Integer requestSuccess;
	private Integer requestFail;
	private Date timeUpdated;

	public PgLogChannelFunction() {
	}

	public PgLogChannelFunction(ChannelFunction channelFunction, String userCode, Integer requestTotal,
			Integer requestSuccess, Integer requestFail, Date timeUpdated) {
		this.channelFunction = channelFunction;
		this.userCode = userCode;
		this.requestTotal = requestTotal;
		this.requestSuccess = requestSuccess;
		this.requestFail = requestFail;
		this.timeUpdated = timeUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "channel_function_id", unique = true)
	public ChannelFunction getChannelFunction() {
		return this.channelFunction;
	}

	public void setChannelFunction(ChannelFunction channelFunction) {
		this.channelFunction = channelFunction;
	}

	@Column(name = "user_code", length = 45)
	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	@Column(name = "request_total")
	@ColumnDefault(value="1")
	@Generated(GenerationTime.INSERT)
	public Integer getRequestTotal() {
		return this.requestTotal;
	}

	public void setRequestTotal(Integer requestTotal) {
		this.requestTotal = requestTotal;
	}

	@Column(name = "request_success")
	@ColumnDefault(value="0")
	@Generated(GenerationTime.INSERT)
	public Integer getRequestSuccess() {
		return this.requestSuccess;
	}

	public void setRequestSuccess(Integer requestSuccess) {
		this.requestSuccess = requestSuccess;
	}

	@Column(name = "request_fail")
	@ColumnDefault(value="0")
	@Generated(GenerationTime.INSERT)
	public Integer getRequestFail() {
		return this.requestFail;
	}

	public void setRequestFail(Integer requestFail) {
		this.requestFail = requestFail;
	}

	// @CreationTimestamp
	// , insertable=false
	@UpdateTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_updated", length = 19)
	public Date getTimeUpdated() {
		return this.timeUpdated;
	}

	public void setTimeUpdated(Date timeUpdated) {
		this.timeUpdated = timeUpdated;
	}

}
