package vn.nganluong.naba.entities;
// Generated Dec 1, 2020 10:42:10 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PgSftp generated by hbm2java
 */
@Entity
@Table(name = "pg_sftp")
public class PgSftp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4876034836072026689L;
	private Integer id;
	private int channelId;
	private Integer pgFunctionId;
	private String host;
	private String userName;
	private String password;
	private Integer port;
	private String remoteDirIn;
	private String remoteDirOut;
	private String remoteSyntaxFileNameOut;
	private String remoteSyntaxOther;
	private String localDirIn;
	private String localDirOut;
	private String localSyntaxFileNameIn;
	private String localSyntaxFileNameOut;
	private String mailSubject;
	private String mailContent;
	private String description;
	private Date timeCreated;
	private Boolean status;

	public PgSftp() {
	}

	public PgSftp(int channelId) {
		this.channelId = channelId;
	}

	public PgSftp(int channelId, Integer pgFunctionId, String host, String userName, String password, Integer port,
			String remoteDirIn, String remoteDirOut, String remoteSyntaxFileNameOut, String remoteSyntaxOther,
			String localDirIn, String localDirOut, String localSyntaxFileNameIn, String localSyntaxFileNameOut,
			String mailSubject, String mailContent, String description, Date timeCreated, Boolean status) {
		this.channelId = channelId;
		this.pgFunctionId = pgFunctionId;
		this.host = host;
		this.userName = userName;
		this.password = password;
		this.port = port;
		this.remoteDirIn = remoteDirIn;
		this.remoteDirOut = remoteDirOut;
		this.remoteSyntaxFileNameOut = remoteSyntaxFileNameOut;
		this.remoteSyntaxOther = remoteSyntaxOther;
		this.localDirIn = localDirIn;
		this.localDirOut = localDirOut;
		this.localSyntaxFileNameIn = localSyntaxFileNameIn;
		this.localSyntaxFileNameOut = localSyntaxFileNameOut;
		this.mailSubject = mailSubject;
		this.mailContent = mailContent;
		this.description = description;
		this.timeCreated = timeCreated;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "channel_id", nullable = false)
	public int getChannelId() {
		return this.channelId;
	}

	public void setChannelId(int channelId) {
		this.channelId = channelId;
	}

	@Column(name = "pg_function_id")
	public Integer getPgFunctionId() {
		return this.pgFunctionId;
	}

	public void setPgFunctionId(Integer pgFunctionId) {
		this.pgFunctionId = pgFunctionId;
	}

	@Column(name = "host")
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "user_name", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "port")
	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	@Column(name = "remote_dir_in")
	public String getRemoteDirIn() {
		return this.remoteDirIn;
	}

	public void setRemoteDirIn(String remoteDirIn) {
		this.remoteDirIn = remoteDirIn;
	}

	@Column(name = "remote_dir_out", length = 45)
	public String getRemoteDirOut() {
		return this.remoteDirOut;
	}

	public void setRemoteDirOut(String remoteDirOut) {
		this.remoteDirOut = remoteDirOut;
	}

	@Column(name = "remote_syntax_file_name_out")
	public String getRemoteSyntaxFileNameOut() {
		return this.remoteSyntaxFileNameOut;
	}

	public void setRemoteSyntaxFileNameOut(String remoteSyntaxFileNameOut) {
		this.remoteSyntaxFileNameOut = remoteSyntaxFileNameOut;
	}

	@Column(name = "remote_syntax_other")
	public String getRemoteSyntaxOther() {
		return this.remoteSyntaxOther;
	}

	public void setRemoteSyntaxOther(String remoteSyntaxOther) {
		this.remoteSyntaxOther = remoteSyntaxOther;
	}

	@Column(name = "local_dir_in")
	public String getLocalDirIn() {
		return this.localDirIn;
	}

	public void setLocalDirIn(String localDirIn) {
		this.localDirIn = localDirIn;
	}

	@Column(name = "local_dir_out")
	public String getLocalDirOut() {
		return this.localDirOut;
	}

	public void setLocalDirOut(String localDirOut) {
		this.localDirOut = localDirOut;
	}

	@Column(name = "local_syntax_file_name_in")
	public String getLocalSyntaxFileNameIn() {
		return this.localSyntaxFileNameIn;
	}

	public void setLocalSyntaxFileNameIn(String localSyntaxFileNameIn) {
		this.localSyntaxFileNameIn = localSyntaxFileNameIn;
	}

	@Column(name = "local_syntax_file_name_out")
	public String getLocalSyntaxFileNameOut() {
		return this.localSyntaxFileNameOut;
	}

	public void setLocalSyntaxFileNameOut(String localSyntaxFileNameOut) {
		this.localSyntaxFileNameOut = localSyntaxFileNameOut;
	}

	@Column(name = "mail_subject", length = 1000)
	public String getMailSubject() {
		return this.mailSubject;
	}

	public void setMailSubject(String mailSubject) {
		this.mailSubject = mailSubject;
	}

	@Column(name = "mail_content", length = 2048)
	public String getMailContent() {
		return this.mailContent;
	}

	public void setMailContent(String mailContent) {
		this.mailContent = mailContent;
	}

	@Column(name = "description", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", length = 19)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
