package vn.nganluong.naba.entities;
// Generated Nov 1, 2020 4:13:02 PM by Hibernate Tools 5.2.12.Final

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PgUser generated by hbm2java
 */
@Entity
@Table(name = "pg_user", uniqueConstraints = { @UniqueConstraint(columnNames = "code"),
		@UniqueConstraint(columnNames = "name") })
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class PgUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7190629138896996474L;
	private Integer id;
	private String name;
	private String code;
	private int endpointId;
	private String prefixUser;
	private Date timeCreated;
	private byte status;

	public PgUser() {
	}

	public PgUser(String name, String code, int endpointId, byte status) {
		this.name = name;
		this.code = code;
		this.endpointId = endpointId;
		this.status = status;
	}

	public PgUser(String name, String code, int endpointId, String prefixUser, Date timeCreated, byte status) {
		this.name = name;
		this.code = code;
		this.endpointId = endpointId;
		this.prefixUser = prefixUser;
		this.timeCreated = timeCreated;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", unique = true, nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "endpoint_id", nullable = false)
	public int getEndpointId() {
		return this.endpointId;
	}

	public void setEndpointId(int endpointId) {
		this.endpointId = endpointId;
	}

	@Column(name = "prefix_user", length = 50)
	public String getPrefixUser() {
		return this.prefixUser;
	}

	public void setPrefixUser(String prefixUser) {
		this.prefixUser = prefixUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "time_created", length = 10)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
