package vn.nganluong.naba.entities;
// Generated Nov 18, 2020 3:51:24 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * VirtualAccount generated by hbm2java
 */
@Entity
@Table(name = "virtual_account", uniqueConstraints = @UniqueConstraint(columnNames = "virtual_account_no"))
public class VirtualAccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4001265192817885862L;
	private Integer id;
	private Channel channel;
	private String virtualAccountNo;
	private String virtualAccountName;
	private String merchantCode;
	private String phoneNumber;
	private Boolean enable;
	private String description;
	private Date timeCreated;
	private Date timeUpdated;
	private Boolean status;

	public VirtualAccount() {
	}

	public VirtualAccount(String virtualAccountNo) {
		this.virtualAccountNo = virtualAccountNo;
	}

	public VirtualAccount(Channel channel, String virtualAccountNo, String virtualAccountName, String merchantCode,
			String phoneNumber, Boolean enable, String description, Date timeCreated, Date timeUpdated, Boolean status) {
		this.channel = channel;
		this.virtualAccountNo = virtualAccountNo;
		this.virtualAccountName = virtualAccountName;
		this.merchantCode = merchantCode;
		this.phoneNumber = phoneNumber;
		this.enable = enable;
		this.description = description;
		this.timeCreated = timeCreated;
		this.timeUpdated = timeUpdated;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "channel_id")
	public Channel getChannel() {
		return this.channel;
	}

	public void setChannel(Channel channel) {
		this.channel = channel;
	}

	@Column(name = "virtual_account_no", unique = true, nullable = false, length = 45)
	public String getVirtualAccountNo() {
		return this.virtualAccountNo;
	}

	public void setVirtualAccountNo(String virtualAccountNo) {
		this.virtualAccountNo = virtualAccountNo;
	}

	@Column(name = "virtual_account_name", length = 100)
	public String getVirtualAccountName() {
		return this.virtualAccountName;
	}

	public void setVirtualAccountName(String virtualAccountName) {
		this.virtualAccountName = virtualAccountName;
	}

	@Column(name = "merchant_code", length = 45)
	public String getMerchantCode() {
		return this.merchantCode;
	}

	public void setMerchantCode(String merchantCode) {
		this.merchantCode = merchantCode;
	}

	@Column(name = "phone_number", length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", length = 19)
	@CreationTimestamp
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_updated", length = 19)
	@UpdateTimestamp
	public Date getTimeUpdated() {
		return this.timeUpdated;
	}

	public void setTimeUpdated(Date timeUpdated) {
		this.timeUpdated = timeUpdated;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "enable")
	public Boolean getEnable() {
		return enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}
}
