package vn.nganluong.naba.entities;
// Generated Dec 12, 2020, 4:50:37 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WebRoles generated by hbm2java
 */
@Entity
@Table(name = "web_roles")
public class WebRoles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3271958968008017724L;
	private Integer id;
	private String name;
	private Boolean status;
	private Set<WebUsersRoles> webUsersRoleses = new HashSet<WebUsersRoles>(0);

	public WebRoles() {
	}

	public WebRoles(String name) {
		this.name = name;
	}

	public WebRoles(String name, Boolean status, Set<WebUsersRoles> webUsersRoleses) {
		this.name = name;
		this.status = status;
		this.webUsersRoleses = webUsersRoleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "webRoles")
	public Set<WebUsersRoles> getWebUsersRoleses() {
		return this.webUsersRoleses;
	}

	public void setWebUsersRoleses(Set<WebUsersRoles> webUsersRoleses) {
		this.webUsersRoleses = webUsersRoleses;
	}

}
