package vn.nganluong.naba.entities;
// Generated Dec 12, 2020, 4:50:37 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * WebUsers generated by hbm2java
 */
@Entity
@Table(name = "web_users", uniqueConstraints = @UniqueConstraint(columnNames = "user_name"))
public class WebUsers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2037824067193474915L;
	private Integer id;
	private String userName;
	private String fullName;
	private String password;
	private Date timeCreated;
	private Date timeUpdated;
	private Boolean status;
	private Set<WebUsersRoles> webUsersRoleses = new HashSet<WebUsersRoles>(0);

	public WebUsers() {
	}

	public WebUsers(String userName, String fullName, String password) {
		this.userName = userName;
		this.fullName = fullName;
		this.password = password;
	}

	public WebUsers(String userName, String fullName, String password, Date timeCreated, Date timeUpdated,
			Boolean status, Set<WebUsersRoles> webUsersRoleses) {
		this.userName = userName;
		this.fullName = fullName;
		this.password = password;
		this.timeCreated = timeCreated;
		this.timeUpdated = timeUpdated;
		this.status = status;
		this.webUsersRoleses = webUsersRoleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_name", unique = true, nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "full_name", nullable = false, length = 100)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", length = 19)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_updated", length = 19)
	public Date getTimeUpdated() {
		return this.timeUpdated;
	}

	public void setTimeUpdated(Date timeUpdated) {
		this.timeUpdated = timeUpdated;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "webUsers")
	public Set<WebUsersRoles> getWebUsersRoleses() {
		return this.webUsersRoleses;
	}

	public void setWebUsersRoleses(Set<WebUsersRoles> webUsersRoleses) {
		this.webUsersRoleses = webUsersRoleses;
	}

}
