package vn.nganluong.naba.entities;
// Generated Dec 12, 2020, 4:50:37 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WebUsersRoles generated by hbm2java
 */
@Entity
@Table(name = "web_users_roles")
public class WebUsersRoles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 498982295686573282L;
	private WebUsersRolesId id;
	private WebRoles webRoles;
	private WebUsers webUsers;

	public WebUsersRoles() {
	}

	public WebUsersRoles(WebUsersRolesId id, WebRoles webRoles, WebUsers webUsers) {
		this.id = id;
		this.webRoles = webRoles;
		this.webUsers = webUsers;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)) })
	public WebUsersRolesId getId() {
		return this.id;
	}

	public void setId(WebUsersRolesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public WebRoles getWebRoles() {
		return this.webRoles;
	}

	public void setWebRoles(WebRoles webRoles) {
		this.webRoles = webRoles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public WebUsers getWebUsers() {
		return this.webUsers;
	}

	public void setWebUsers(WebUsers webUsers) {
		this.webUsers = webUsers;
	}

}
